/*
 * Copyright (c) 2019, Juraj Papp
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the copyright holder nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package theleo.jstruct.bridge;

import theleo.jstruct.hidden.R1;

/**
 * Defines an interface with methods used to
 * retrieve and store values to memory.
 * The first long argument is an address and is
 * assumed to be aligned according to the type of method called.
 * 
 * <pre>
 * 
 * Method names follor the following format:
 * 
 * Method type:
 * 
 * g - get (takes a long address)
 * p - put (takes long address, value of its type)
 * x - get address from index
 * 
 * Type:
 * 
 * Z - boolean
 * B - byte
 * C - char
 * S - short
 * I - int
 * J - long
 * F - float
 * D - double
 * L - object
 * R - struct reference
 * 
 * Operators:
 * 
 * Add, Sub, Mul, Div, Mod,
 * And, Or, Xor, LL(left shift), RR(right shift), RRR(triple right shift)
 * 
 * PrI (pre-increment)
 * PoI (post-increment)
 * PrD (pre-decrement)
 * PoD (post-decrement)
 * 
 * </pre>
 * 
 * @author Juraj Papp
 */
public interface Bridge {
	
	public <T> T gL(final R1 r, final long l, int i);
	public <T> T pL(final R1 r, final long l, int i, T o);
	
//	public <T> T gL(final R1.B r, final long l, int i);
//	public <T> T pL(final R1.B r, final long l, int i, T o);
	
	public <T> T pR(final R1 r, final long l, int add, int i, final R1 r2, final long l2);
	public <T> T pR(final R1 r, final long l, final R1 r2, final long l2);
	
	public boolean gZ(final R1 r, final long l);
	public boolean pZ(final R1 r, final long l, final boolean f);
	public byte gB(final R1 r, final long l);
	public byte pB(final R1 r, final long l, final byte f);
	public char gC(final R1 r, final long l);
	public char pC(final R1 r, final long l, final char f);
	public short gS(final R1 r, final long l);
	public short pS(final R1 r, final long l, final short f);
	public int gI(final R1 r, final long l);
	public int pI(final R1 r, final long l, final int f);
	public long gJ(final R1 r, final long l);
	public long pJ(final R1 r, final long l, final long f);
	public float gF(final R1 r, final long l);
	public float pF(final R1 r, final long l, final float f);
	public double gD(final R1 r, final long l);
	public double pD(final R1 r, final long l, final double f);
	
	public boolean pZAnd(final R1 r, final long l, boolean f);
	public boolean pZOr(final R1 r, final long l, boolean f);
	public boolean pZXor(final R1 r, final long l, boolean f);
	public byte pBAdd(final R1 r, final long l, byte f);
	public byte pBSub(final R1 r, final long l, byte f);
	public byte pBMul(final R1 r, final long l, byte f);
	public byte pBDiv(final R1 r, final long l, byte f);
	public byte pBMod(final R1 r, final long l, byte f);
	public byte pBAnd(final R1 r, final long l, byte f);
	public byte pBOr(final R1 r, final long l, byte f);
	public byte pBXor(final R1 r, final long l, byte f);
	public byte pBLL(final R1 r, final long l, byte f);
	public byte pBRR(final R1 r, final long l, byte f);
	public byte pBRRR(final R1 r, final long l, byte f);
	public char pCAdd(final R1 r, final long l, char f);
	public char pCSub(final R1 r, final long l, char f);
	public char pCMul(final R1 r, final long l, char f);
	public char pCDiv(final R1 r, final long l, char f);
	public char pCMod(final R1 r, final long l, char f);
	public char pCAnd(final R1 r, final long l, char f);
	public char pCOr(final R1 r, final long l, char f);
	public char pCXor(final R1 r, final long l, char f);
	public char pCLL(final R1 r, final long l, char f);
	public char pCRR(final R1 r, final long l, char f);
	public char pCRRR(final R1 r, final long l, char f);
	public short pSAdd(final R1 r, final long l, short f);
	public short pSSub(final R1 r, final long l, short f);
	public short pSMul(final R1 r, final long l, short f);
	public short pSDiv(final R1 r, final long l, short f);
	public short pSMod(final R1 r, final long l, short f);
	public short pSAnd(final R1 r, final long l, short f);
	public short pSOr(final R1 r, final long l, short f);
	public short pSXor(final R1 r, final long l, short f);
	public short pSLL(final R1 r, final long l, short f);
	public short pSRR(final R1 r, final long l, short f);
	public short pSRRR(final R1 r, final long l, short f);
	public int pIAdd(final R1 r, final long l, int f);
	public int pISub(final R1 r, final long l, int f);
	public int pIMul(final R1 r, final long l, int f);
	public int pIDiv(final R1 r, final long l, int f);
	public int pIMod(final R1 r, final long l, int f);
	public int pIAnd(final R1 r, final long l, int f);
	public int pIOr(final R1 r, final long l, int f);
	public int pIXor(final R1 r, final long l, int f);
	public int pILL(final R1 r, final long l, int f);
	public int pIRR(final R1 r, final long l, int f);
	public int pIRRR(final R1 r, final long l, int f);
	public long pJAdd(final R1 r, final long l, long f);
	public long pJSub(final R1 r, final long l, long f);
	public long pJMul(final R1 r, final long l, long f);
	public long pJDiv(final R1 r, final long l, long f);
	public long pJMod(final R1 r, final long l, long f);
	public long pJAnd(final R1 r, final long l, long f);
	public long pJOr(final R1 r, final long l, long f);
	public long pJXor(final R1 r, final long l, long f);
	public long pJLL(final R1 r, final long l, long f);
	public long pJRR(final R1 r, final long l, long f);
	public long pJRRR(final R1 r, final long l, long f);
	public float pFAdd(final R1 r, final long l, float f);
	public float pFSub(final R1 r, final long l, float f);
	public float pFMul(final R1 r, final long l, float f);
	public float pFDiv(final R1 r, final long l, float f);
	public float pFMod(final R1 r, final long l, float f);
	public double pDAdd(final R1 r, final long l, double f);
	public double pDSub(final R1 r, final long l, double f);
	public double pDMul(final R1 r, final long l, double f);
	public double pDDiv(final R1 r, final long l, double f);
	public double pDMod(final R1 r, final long l, double f);
	
	public boolean gZ(final R1.N r, final long l);
	public boolean pZ(final R1.N r, final long l, final boolean f);
	public byte gB(final R1.N r, final long l);
	public byte pB(final R1.N r, final long l, final byte f);
	public char gC(final R1.N r, final long l);
	public char pC(final R1.N r, final long l, final char f);
	public short gS(final R1.N r, final long l);
	public short pS(final R1.N r, final long l, final short f);
	public int gI(final R1.N r, final long l);
	public int pI(final R1.N r, final long l, final int f);
	public long gJ(final R1.N r, final long l);
	public long pJ(final R1.N r, final long l, final long f);
	public float gF(final R1.N r, final long l);
	public float pF(final R1.N r, final long l, final float f);
	public double gD(final R1.N r, final long l);
	public double pD(final R1.N r, final long l, final double f);
	
	public boolean gZ(final R1.A r, final long l);
	public boolean pZ(final R1.A r, final long l, final boolean f);
	public byte gB(final R1.A r, final long l);
	public byte pB(final R1.A r, final long l, final byte f);
	public char gC(final R1.A r, final long l);
	public char pC(final R1.A r, final long l, final char f);
	public short gS(final R1.A r, final long l);
	public short pS(final R1.A r, final long l, final short f);
	public int gI(final R1.A r, final long l);
	public int pI(final R1.A r, final long l, final int f);
	public long gJ(final R1.A r, final long l);
	public long pJ(final R1.A r, final long l, final long f);
	public float gF(final R1.A r, final long l);
	public float pF(final R1.A r, final long l, final float f);
	public double gD(final R1.A r, final long l);
	public double pD(final R1.A r, final long l, final double f);

	public boolean gZ(final R1.B r, final long l);
	public boolean pZ(final R1.B r, final long l, final boolean f);
	public byte gB(final R1.B r, final long l);
	public byte pB(final R1.B r, final long l, final byte f);
	public char gC(final R1.B r, final long l);
	public char pC(final R1.B r, final long l, final char f);
	public short gS(final R1.B r, final long l);
	public short pS(final R1.B r, final long l, final short f);
	public int gI(final R1.B r, final long l);
	public int pI(final R1.B r, final long l, final int f);
	public long gJ(final R1.B r, final long l);
	public long pJ(final R1.B r, final long l, final long f);
	public float gF(final R1.B r, final long l);
	public float pF(final R1.B r, final long l, final float f);
	public double gD(final R1.B r, final long l);
	public double pD(final R1.B r, final long l, final double f);

	public boolean gZ(final R1.C r, final long l);
	public boolean pZ(final R1.C r, final long l, final boolean f);
	public byte gB(final R1.C r, final long l);
	public byte pB(final R1.C r, final long l, final byte f);
	public char gC(final R1.C r, final long l);
	public char pC(final R1.C r, final long l, final char f);
	public short gS(final R1.C r, final long l);
	public short pS(final R1.C r, final long l, final short f);
	public int gI(final R1.C r, final long l);
	public int pI(final R1.C r, final long l, final int f);
	public long gJ(final R1.C r, final long l);
	public long pJ(final R1.C r, final long l, final long f);
	public float gF(final R1.C r, final long l);
	public float pF(final R1.C r, final long l, final float f);
	public double gD(final R1.C r, final long l);
	public double pD(final R1.C r, final long l, final double f);

	public boolean gZ(final R1.S r, final long l);
	public boolean pZ(final R1.S r, final long l, final boolean f);
	public byte gB(final R1.S r, final long l);
	public byte pB(final R1.S r, final long l, final byte f);
	public char gC(final R1.S r, final long l);
	public char pC(final R1.S r, final long l, final char f);
	public short gS(final R1.S r, final long l);
	public short pS(final R1.S r, final long l, final short f);
	public int gI(final R1.S r, final long l);
	public int pI(final R1.S r, final long l, final int f);
	public long gJ(final R1.S r, final long l);
	public long pJ(final R1.S r, final long l, final long f);
	public float gF(final R1.S r, final long l);
	public float pF(final R1.S r, final long l, final float f);
	public double gD(final R1.S r, final long l);
	public double pD(final R1.S r, final long l, final double f);

	public boolean gZ(final R1.I r, final long l);
	public boolean pZ(final R1.I r, final long l, final boolean f);
	public byte gB(final R1.I r, final long l);
	public byte pB(final R1.I r, final long l, final byte f);
	public char gC(final R1.I r, final long l);
	public char pC(final R1.I r, final long l, final char f);
	public short gS(final R1.I r, final long l);
	public short pS(final R1.I r, final long l, final short f);
	public int gI(final R1.I r, final long l);
	public int pI(final R1.I r, final long l, final int f);
	public long gJ(final R1.I r, final long l);
	public long pJ(final R1.I r, final long l, final long f);
	public float gF(final R1.I r, final long l);
	public float pF(final R1.I r, final long l, final float f);
	public double gD(final R1.I r, final long l);
	public double pD(final R1.I r, final long l, final double f);

	public boolean gZ(final R1.L r, final long l);
	public boolean pZ(final R1.L r, final long l, final boolean f);
	public byte gB(final R1.L r, final long l);
	public byte pB(final R1.L r, final long l, final byte f);
	public char gC(final R1.L r, final long l);
	public char pC(final R1.L r, final long l, final char f);
	public short gS(final R1.L r, final long l);
	public short pS(final R1.L r, final long l, final short f);
	public int gI(final R1.L r, final long l);
	public int pI(final R1.L r, final long l, final int f);
	public long gJ(final R1.L r, final long l);
	public long pJ(final R1.L r, final long l, final long f);
	public float gF(final R1.L r, final long l);
	public float pF(final R1.L r, final long l, final float f);
	public double gD(final R1.L r, final long l);
	public double pD(final R1.L r, final long l, final double f);

	public boolean gZ(final R1.F r, final long l);
	public boolean pZ(final R1.F r, final long l, final boolean f);
	public byte gB(final R1.F r, final long l);
	public byte pB(final R1.F r, final long l, final byte f);
	public char gC(final R1.F r, final long l);
	public char pC(final R1.F r, final long l, final char f);
	public short gS(final R1.F r, final long l);
	public short pS(final R1.F r, final long l, final short f);
	public int gI(final R1.F r, final long l);
	public int pI(final R1.F r, final long l, final int f);
	public long gJ(final R1.F r, final long l);
	public long pJ(final R1.F r, final long l, final long f);
	public float gF(final R1.F r, final long l);
	public float pF(final R1.F r, final long l, final float f);
	public double gD(final R1.F r, final long l);
	public double pD(final R1.F r, final long l, final double f);

	public boolean gZ(final R1.D r, final long l);
	public boolean pZ(final R1.D r, final long l, final boolean f);
	public byte gB(final R1.D r, final long l);
	public byte pB(final R1.D r, final long l, final byte f);
	public char gC(final R1.D r, final long l);
	public char pC(final R1.D r, final long l, final char f);
	public short gS(final R1.D r, final long l);
	public short pS(final R1.D r, final long l, final short f);
	public int gI(final R1.D r, final long l);
	public int pI(final R1.D r, final long l, final int f);
	public long gJ(final R1.D r, final long l);
	public long pJ(final R1.D r, final long l, final long f);
	public float gF(final R1.D r, final long l);
	public float pF(final R1.D r, final long l, final float f);
	public double gD(final R1.D r, final long l);
	public double pD(final R1.D r, final long l, final double f);
	
	public boolean pZAnd(final R1.A r, final long l, boolean f);
	public boolean pZOr(final R1.A r, final long l, boolean f);
	public boolean pZXor(final R1.A r, final long l, boolean f);
	public byte pBAdd(final R1.A r, final long l, byte f);
	public byte pBSub(final R1.A r, final long l, byte f);
	public byte pBMul(final R1.A r, final long l, byte f);
	public byte pBDiv(final R1.A r, final long l, byte f);
	public byte pBMod(final R1.A r, final long l, byte f);
	public byte pBAnd(final R1.A r, final long l, byte f);
	public byte pBOr(final R1.A r, final long l, byte f);
	public byte pBXor(final R1.A r, final long l, byte f);
	public byte pBLL(final R1.A r, final long l, byte f);
	public byte pBRR(final R1.A r, final long l, byte f);
	public byte pBRRR(final R1.A r, final long l, byte f);
	public char pCAdd(final R1.A r, final long l, char f);
	public char pCSub(final R1.A r, final long l, char f);
	public char pCMul(final R1.A r, final long l, char f);
	public char pCDiv(final R1.A r, final long l, char f);
	public char pCMod(final R1.A r, final long l, char f);
	public char pCAnd(final R1.A r, final long l, char f);
	public char pCOr(final R1.A r, final long l, char f);
	public char pCXor(final R1.A r, final long l, char f);
	public char pCLL(final R1.A r, final long l, char f);
	public char pCRR(final R1.A r, final long l, char f);
	public char pCRRR(final R1.A r, final long l, char f);
	public short pSAdd(final R1.A r, final long l, short f);
	public short pSSub(final R1.A r, final long l, short f);
	public short pSMul(final R1.A r, final long l, short f);
	public short pSDiv(final R1.A r, final long l, short f);
	public short pSMod(final R1.A r, final long l, short f);
	public short pSAnd(final R1.A r, final long l, short f);
	public short pSOr(final R1.A r, final long l, short f);
	public short pSXor(final R1.A r, final long l, short f);
	public short pSLL(final R1.A r, final long l, short f);
	public short pSRR(final R1.A r, final long l, short f);
	public short pSRRR(final R1.A r, final long l, short f);
	public int pIAdd(final R1.A r, final long l, int f);
	public int pISub(final R1.A r, final long l, int f);
	public int pIMul(final R1.A r, final long l, int f);
	public int pIDiv(final R1.A r, final long l, int f);
	public int pIMod(final R1.A r, final long l, int f);
	public int pIAnd(final R1.A r, final long l, int f);
	public int pIOr(final R1.A r, final long l, int f);
	public int pIXor(final R1.A r, final long l, int f);
	public int pILL(final R1.A r, final long l, int f);
	public int pIRR(final R1.A r, final long l, int f);
	public int pIRRR(final R1.A r, final long l, int f);
	public long pJAdd(final R1.A r, final long l, long f);
	public long pJSub(final R1.A r, final long l, long f);
	public long pJMul(final R1.A r, final long l, long f);
	public long pJDiv(final R1.A r, final long l, long f);
	public long pJMod(final R1.A r, final long l, long f);
	public long pJAnd(final R1.A r, final long l, long f);
	public long pJOr(final R1.A r, final long l, long f);
	public long pJXor(final R1.A r, final long l, long f);
	public long pJLL(final R1.A r, final long l, long f);
	public long pJRR(final R1.A r, final long l, long f);
	public long pJRRR(final R1.A r, final long l, long f);
	public float pFAdd(final R1.A r, final long l, float f);
	public float pFSub(final R1.A r, final long l, float f);
	public float pFMul(final R1.A r, final long l, float f);
	public float pFDiv(final R1.A r, final long l, float f);
	public float pFMod(final R1.A r, final long l, float f);
	public double pDAdd(final R1.A r, final long l, double f);
	public double pDSub(final R1.A r, final long l, double f);
	public double pDMul(final R1.A r, final long l, double f);
	public double pDDiv(final R1.A r, final long l, double f);
	public double pDMod(final R1.A r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.B r, final long l, boolean f);
	public boolean pZOr(final R1.B r, final long l, boolean f);
	public boolean pZXor(final R1.B r, final long l, boolean f);
	public byte pBAdd(final R1.B r, final long l, byte f);
	public byte pBSub(final R1.B r, final long l, byte f);
	public byte pBMul(final R1.B r, final long l, byte f);
	public byte pBDiv(final R1.B r, final long l, byte f);
	public byte pBMod(final R1.B r, final long l, byte f);
	public byte pBAnd(final R1.B r, final long l, byte f);
	public byte pBOr(final R1.B r, final long l, byte f);
	public byte pBXor(final R1.B r, final long l, byte f);
	public byte pBLL(final R1.B r, final long l, byte f);
	public byte pBRR(final R1.B r, final long l, byte f);
	public byte pBRRR(final R1.B r, final long l, byte f);
	public char pCAdd(final R1.B r, final long l, char f);
	public char pCSub(final R1.B r, final long l, char f);
	public char pCMul(final R1.B r, final long l, char f);
	public char pCDiv(final R1.B r, final long l, char f);
	public char pCMod(final R1.B r, final long l, char f);
	public char pCAnd(final R1.B r, final long l, char f);
	public char pCOr(final R1.B r, final long l, char f);
	public char pCXor(final R1.B r, final long l, char f);
	public char pCLL(final R1.B r, final long l, char f);
	public char pCRR(final R1.B r, final long l, char f);
	public char pCRRR(final R1.B r, final long l, char f);
	public short pSAdd(final R1.B r, final long l, short f);
	public short pSSub(final R1.B r, final long l, short f);
	public short pSMul(final R1.B r, final long l, short f);
	public short pSDiv(final R1.B r, final long l, short f);
	public short pSMod(final R1.B r, final long l, short f);
	public short pSAnd(final R1.B r, final long l, short f);
	public short pSOr(final R1.B r, final long l, short f);
	public short pSXor(final R1.B r, final long l, short f);
	public short pSLL(final R1.B r, final long l, short f);
	public short pSRR(final R1.B r, final long l, short f);
	public short pSRRR(final R1.B r, final long l, short f);
	public int pIAdd(final R1.B r, final long l, int f);
	public int pISub(final R1.B r, final long l, int f);
	public int pIMul(final R1.B r, final long l, int f);
	public int pIDiv(final R1.B r, final long l, int f);
	public int pIMod(final R1.B r, final long l, int f);
	public int pIAnd(final R1.B r, final long l, int f);
	public int pIOr(final R1.B r, final long l, int f);
	public int pIXor(final R1.B r, final long l, int f);
	public int pILL(final R1.B r, final long l, int f);
	public int pIRR(final R1.B r, final long l, int f);
	public int pIRRR(final R1.B r, final long l, int f);
	public long pJAdd(final R1.B r, final long l, long f);
	public long pJSub(final R1.B r, final long l, long f);
	public long pJMul(final R1.B r, final long l, long f);
	public long pJDiv(final R1.B r, final long l, long f);
	public long pJMod(final R1.B r, final long l, long f);
	public long pJAnd(final R1.B r, final long l, long f);
	public long pJOr(final R1.B r, final long l, long f);
	public long pJXor(final R1.B r, final long l, long f);
	public long pJLL(final R1.B r, final long l, long f);
	public long pJRR(final R1.B r, final long l, long f);
	public long pJRRR(final R1.B r, final long l, long f);
	public float pFAdd(final R1.B r, final long l, float f);
	public float pFSub(final R1.B r, final long l, float f);
	public float pFMul(final R1.B r, final long l, float f);
	public float pFDiv(final R1.B r, final long l, float f);
	public float pFMod(final R1.B r, final long l, float f);
	public double pDAdd(final R1.B r, final long l, double f);
	public double pDSub(final R1.B r, final long l, double f);
	public double pDMul(final R1.B r, final long l, double f);
	public double pDDiv(final R1.B r, final long l, double f);
	public double pDMod(final R1.B r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.C r, final long l, boolean f);
	public boolean pZOr(final R1.C r, final long l, boolean f);
	public boolean pZXor(final R1.C r, final long l, boolean f);
	public byte pBAdd(final R1.C r, final long l, byte f);
	public byte pBSub(final R1.C r, final long l, byte f);
	public byte pBMul(final R1.C r, final long l, byte f);
	public byte pBDiv(final R1.C r, final long l, byte f);
	public byte pBMod(final R1.C r, final long l, byte f);
	public byte pBAnd(final R1.C r, final long l, byte f);
	public byte pBOr(final R1.C r, final long l, byte f);
	public byte pBXor(final R1.C r, final long l, byte f);
	public byte pBLL(final R1.C r, final long l, byte f);
	public byte pBRR(final R1.C r, final long l, byte f);
	public byte pBRRR(final R1.C r, final long l, byte f);
	public char pCAdd(final R1.C r, final long l, char f);
	public char pCSub(final R1.C r, final long l, char f);
	public char pCMul(final R1.C r, final long l, char f);
	public char pCDiv(final R1.C r, final long l, char f);
	public char pCMod(final R1.C r, final long l, char f);
	public char pCAnd(final R1.C r, final long l, char f);
	public char pCOr(final R1.C r, final long l, char f);
	public char pCXor(final R1.C r, final long l, char f);
	public char pCLL(final R1.C r, final long l, char f);
	public char pCRR(final R1.C r, final long l, char f);
	public char pCRRR(final R1.C r, final long l, char f);
	public short pSAdd(final R1.C r, final long l, short f);
	public short pSSub(final R1.C r, final long l, short f);
	public short pSMul(final R1.C r, final long l, short f);
	public short pSDiv(final R1.C r, final long l, short f);
	public short pSMod(final R1.C r, final long l, short f);
	public short pSAnd(final R1.C r, final long l, short f);
	public short pSOr(final R1.C r, final long l, short f);
	public short pSXor(final R1.C r, final long l, short f);
	public short pSLL(final R1.C r, final long l, short f);
	public short pSRR(final R1.C r, final long l, short f);
	public short pSRRR(final R1.C r, final long l, short f);
	public int pIAdd(final R1.C r, final long l, int f);
	public int pISub(final R1.C r, final long l, int f);
	public int pIMul(final R1.C r, final long l, int f);
	public int pIDiv(final R1.C r, final long l, int f);
	public int pIMod(final R1.C r, final long l, int f);
	public int pIAnd(final R1.C r, final long l, int f);
	public int pIOr(final R1.C r, final long l, int f);
	public int pIXor(final R1.C r, final long l, int f);
	public int pILL(final R1.C r, final long l, int f);
	public int pIRR(final R1.C r, final long l, int f);
	public int pIRRR(final R1.C r, final long l, int f);
	public long pJAdd(final R1.C r, final long l, long f);
	public long pJSub(final R1.C r, final long l, long f);
	public long pJMul(final R1.C r, final long l, long f);
	public long pJDiv(final R1.C r, final long l, long f);
	public long pJMod(final R1.C r, final long l, long f);
	public long pJAnd(final R1.C r, final long l, long f);
	public long pJOr(final R1.C r, final long l, long f);
	public long pJXor(final R1.C r, final long l, long f);
	public long pJLL(final R1.C r, final long l, long f);
	public long pJRR(final R1.C r, final long l, long f);
	public long pJRRR(final R1.C r, final long l, long f);
	public float pFAdd(final R1.C r, final long l, float f);
	public float pFSub(final R1.C r, final long l, float f);
	public float pFMul(final R1.C r, final long l, float f);
	public float pFDiv(final R1.C r, final long l, float f);
	public float pFMod(final R1.C r, final long l, float f);
	public double pDAdd(final R1.C r, final long l, double f);
	public double pDSub(final R1.C r, final long l, double f);
	public double pDMul(final R1.C r, final long l, double f);
	public double pDDiv(final R1.C r, final long l, double f);
	public double pDMod(final R1.C r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.S r, final long l, boolean f);
	public boolean pZOr(final R1.S r, final long l, boolean f);
	public boolean pZXor(final R1.S r, final long l, boolean f);
	public byte pBAdd(final R1.S r, final long l, byte f);
	public byte pBSub(final R1.S r, final long l, byte f);
	public byte pBMul(final R1.S r, final long l, byte f);
	public byte pBDiv(final R1.S r, final long l, byte f);
	public byte pBMod(final R1.S r, final long l, byte f);
	public byte pBAnd(final R1.S r, final long l, byte f);
	public byte pBOr(final R1.S r, final long l, byte f);
	public byte pBXor(final R1.S r, final long l, byte f);
	public byte pBLL(final R1.S r, final long l, byte f);
	public byte pBRR(final R1.S r, final long l, byte f);
	public byte pBRRR(final R1.S r, final long l, byte f);
	public char pCAdd(final R1.S r, final long l, char f);
	public char pCSub(final R1.S r, final long l, char f);
	public char pCMul(final R1.S r, final long l, char f);
	public char pCDiv(final R1.S r, final long l, char f);
	public char pCMod(final R1.S r, final long l, char f);
	public char pCAnd(final R1.S r, final long l, char f);
	public char pCOr(final R1.S r, final long l, char f);
	public char pCXor(final R1.S r, final long l, char f);
	public char pCLL(final R1.S r, final long l, char f);
	public char pCRR(final R1.S r, final long l, char f);
	public char pCRRR(final R1.S r, final long l, char f);
	public short pSAdd(final R1.S r, final long l, short f);
	public short pSSub(final R1.S r, final long l, short f);
	public short pSMul(final R1.S r, final long l, short f);
	public short pSDiv(final R1.S r, final long l, short f);
	public short pSMod(final R1.S r, final long l, short f);
	public short pSAnd(final R1.S r, final long l, short f);
	public short pSOr(final R1.S r, final long l, short f);
	public short pSXor(final R1.S r, final long l, short f);
	public short pSLL(final R1.S r, final long l, short f);
	public short pSRR(final R1.S r, final long l, short f);
	public short pSRRR(final R1.S r, final long l, short f);
	public int pIAdd(final R1.S r, final long l, int f);
	public int pISub(final R1.S r, final long l, int f);
	public int pIMul(final R1.S r, final long l, int f);
	public int pIDiv(final R1.S r, final long l, int f);
	public int pIMod(final R1.S r, final long l, int f);
	public int pIAnd(final R1.S r, final long l, int f);
	public int pIOr(final R1.S r, final long l, int f);
	public int pIXor(final R1.S r, final long l, int f);
	public int pILL(final R1.S r, final long l, int f);
	public int pIRR(final R1.S r, final long l, int f);
	public int pIRRR(final R1.S r, final long l, int f);
	public long pJAdd(final R1.S r, final long l, long f);
	public long pJSub(final R1.S r, final long l, long f);
	public long pJMul(final R1.S r, final long l, long f);
	public long pJDiv(final R1.S r, final long l, long f);
	public long pJMod(final R1.S r, final long l, long f);
	public long pJAnd(final R1.S r, final long l, long f);
	public long pJOr(final R1.S r, final long l, long f);
	public long pJXor(final R1.S r, final long l, long f);
	public long pJLL(final R1.S r, final long l, long f);
	public long pJRR(final R1.S r, final long l, long f);
	public long pJRRR(final R1.S r, final long l, long f);
	public float pFAdd(final R1.S r, final long l, float f);
	public float pFSub(final R1.S r, final long l, float f);
	public float pFMul(final R1.S r, final long l, float f);
	public float pFDiv(final R1.S r, final long l, float f);
	public float pFMod(final R1.S r, final long l, float f);
	public double pDAdd(final R1.S r, final long l, double f);
	public double pDSub(final R1.S r, final long l, double f);
	public double pDMul(final R1.S r, final long l, double f);
	public double pDDiv(final R1.S r, final long l, double f);
	public double pDMod(final R1.S r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.I r, final long l, boolean f);
	public boolean pZOr(final R1.I r, final long l, boolean f);
	public boolean pZXor(final R1.I r, final long l, boolean f);
	public byte pBAdd(final R1.I r, final long l, byte f);
	public byte pBSub(final R1.I r, final long l, byte f);
	public byte pBMul(final R1.I r, final long l, byte f);
	public byte pBDiv(final R1.I r, final long l, byte f);
	public byte pBMod(final R1.I r, final long l, byte f);
	public byte pBAnd(final R1.I r, final long l, byte f);
	public byte pBOr(final R1.I r, final long l, byte f);
	public byte pBXor(final R1.I r, final long l, byte f);
	public byte pBLL(final R1.I r, final long l, byte f);
	public byte pBRR(final R1.I r, final long l, byte f);
	public byte pBRRR(final R1.I r, final long l, byte f);
	public char pCAdd(final R1.I r, final long l, char f);
	public char pCSub(final R1.I r, final long l, char f);
	public char pCMul(final R1.I r, final long l, char f);
	public char pCDiv(final R1.I r, final long l, char f);
	public char pCMod(final R1.I r, final long l, char f);
	public char pCAnd(final R1.I r, final long l, char f);
	public char pCOr(final R1.I r, final long l, char f);
	public char pCXor(final R1.I r, final long l, char f);
	public char pCLL(final R1.I r, final long l, char f);
	public char pCRR(final R1.I r, final long l, char f);
	public char pCRRR(final R1.I r, final long l, char f);
	public short pSAdd(final R1.I r, final long l, short f);
	public short pSSub(final R1.I r, final long l, short f);
	public short pSMul(final R1.I r, final long l, short f);
	public short pSDiv(final R1.I r, final long l, short f);
	public short pSMod(final R1.I r, final long l, short f);
	public short pSAnd(final R1.I r, final long l, short f);
	public short pSOr(final R1.I r, final long l, short f);
	public short pSXor(final R1.I r, final long l, short f);
	public short pSLL(final R1.I r, final long l, short f);
	public short pSRR(final R1.I r, final long l, short f);
	public short pSRRR(final R1.I r, final long l, short f);
	public int pIAdd(final R1.I r, final long l, int f);
	public int pISub(final R1.I r, final long l, int f);
	public int pIMul(final R1.I r, final long l, int f);
	public int pIDiv(final R1.I r, final long l, int f);
	public int pIMod(final R1.I r, final long l, int f);
	public int pIAnd(final R1.I r, final long l, int f);
	public int pIOr(final R1.I r, final long l, int f);
	public int pIXor(final R1.I r, final long l, int f);
	public int pILL(final R1.I r, final long l, int f);
	public int pIRR(final R1.I r, final long l, int f);
	public int pIRRR(final R1.I r, final long l, int f);
	public long pJAdd(final R1.I r, final long l, long f);
	public long pJSub(final R1.I r, final long l, long f);
	public long pJMul(final R1.I r, final long l, long f);
	public long pJDiv(final R1.I r, final long l, long f);
	public long pJMod(final R1.I r, final long l, long f);
	public long pJAnd(final R1.I r, final long l, long f);
	public long pJOr(final R1.I r, final long l, long f);
	public long pJXor(final R1.I r, final long l, long f);
	public long pJLL(final R1.I r, final long l, long f);
	public long pJRR(final R1.I r, final long l, long f);
	public long pJRRR(final R1.I r, final long l, long f);
	public float pFAdd(final R1.I r, final long l, float f);
	public float pFSub(final R1.I r, final long l, float f);
	public float pFMul(final R1.I r, final long l, float f);
	public float pFDiv(final R1.I r, final long l, float f);
	public float pFMod(final R1.I r, final long l, float f);
	public double pDAdd(final R1.I r, final long l, double f);
	public double pDSub(final R1.I r, final long l, double f);
	public double pDMul(final R1.I r, final long l, double f);
	public double pDDiv(final R1.I r, final long l, double f);
	public double pDMod(final R1.I r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.L r, final long l, boolean f);
	public boolean pZOr(final R1.L r, final long l, boolean f);
	public boolean pZXor(final R1.L r, final long l, boolean f);
	public byte pBAdd(final R1.L r, final long l, byte f);
	public byte pBSub(final R1.L r, final long l, byte f);
	public byte pBMul(final R1.L r, final long l, byte f);
	public byte pBDiv(final R1.L r, final long l, byte f);
	public byte pBMod(final R1.L r, final long l, byte f);
	public byte pBAnd(final R1.L r, final long l, byte f);
	public byte pBOr(final R1.L r, final long l, byte f);
	public byte pBXor(final R1.L r, final long l, byte f);
	public byte pBLL(final R1.L r, final long l, byte f);
	public byte pBRR(final R1.L r, final long l, byte f);
	public byte pBRRR(final R1.L r, final long l, byte f);
	public char pCAdd(final R1.L r, final long l, char f);
	public char pCSub(final R1.L r, final long l, char f);
	public char pCMul(final R1.L r, final long l, char f);
	public char pCDiv(final R1.L r, final long l, char f);
	public char pCMod(final R1.L r, final long l, char f);
	public char pCAnd(final R1.L r, final long l, char f);
	public char pCOr(final R1.L r, final long l, char f);
	public char pCXor(final R1.L r, final long l, char f);
	public char pCLL(final R1.L r, final long l, char f);
	public char pCRR(final R1.L r, final long l, char f);
	public char pCRRR(final R1.L r, final long l, char f);
	public short pSAdd(final R1.L r, final long l, short f);
	public short pSSub(final R1.L r, final long l, short f);
	public short pSMul(final R1.L r, final long l, short f);
	public short pSDiv(final R1.L r, final long l, short f);
	public short pSMod(final R1.L r, final long l, short f);
	public short pSAnd(final R1.L r, final long l, short f);
	public short pSOr(final R1.L r, final long l, short f);
	public short pSXor(final R1.L r, final long l, short f);
	public short pSLL(final R1.L r, final long l, short f);
	public short pSRR(final R1.L r, final long l, short f);
	public short pSRRR(final R1.L r, final long l, short f);
	public int pIAdd(final R1.L r, final long l, int f);
	public int pISub(final R1.L r, final long l, int f);
	public int pIMul(final R1.L r, final long l, int f);
	public int pIDiv(final R1.L r, final long l, int f);
	public int pIMod(final R1.L r, final long l, int f);
	public int pIAnd(final R1.L r, final long l, int f);
	public int pIOr(final R1.L r, final long l, int f);
	public int pIXor(final R1.L r, final long l, int f);
	public int pILL(final R1.L r, final long l, int f);
	public int pIRR(final R1.L r, final long l, int f);
	public int pIRRR(final R1.L r, final long l, int f);
	public long pJAdd(final R1.L r, final long l, long f);
	public long pJSub(final R1.L r, final long l, long f);
	public long pJMul(final R1.L r, final long l, long f);
	public long pJDiv(final R1.L r, final long l, long f);
	public long pJMod(final R1.L r, final long l, long f);
	public long pJAnd(final R1.L r, final long l, long f);
	public long pJOr(final R1.L r, final long l, long f);
	public long pJXor(final R1.L r, final long l, long f);
	public long pJLL(final R1.L r, final long l, long f);
	public long pJRR(final R1.L r, final long l, long f);
	public long pJRRR(final R1.L r, final long l, long f);
	public float pFAdd(final R1.L r, final long l, float f);
	public float pFSub(final R1.L r, final long l, float f);
	public float pFMul(final R1.L r, final long l, float f);
	public float pFDiv(final R1.L r, final long l, float f);
	public float pFMod(final R1.L r, final long l, float f);
	public double pDAdd(final R1.L r, final long l, double f);
	public double pDSub(final R1.L r, final long l, double f);
	public double pDMul(final R1.L r, final long l, double f);
	public double pDDiv(final R1.L r, final long l, double f);
	public double pDMod(final R1.L r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.F r, final long l, boolean f);
	public boolean pZOr(final R1.F r, final long l, boolean f);
	public boolean pZXor(final R1.F r, final long l, boolean f);
	public byte pBAdd(final R1.F r, final long l, byte f);
	public byte pBSub(final R1.F r, final long l, byte f);
	public byte pBMul(final R1.F r, final long l, byte f);
	public byte pBDiv(final R1.F r, final long l, byte f);
	public byte pBMod(final R1.F r, final long l, byte f);
	public byte pBAnd(final R1.F r, final long l, byte f);
	public byte pBOr(final R1.F r, final long l, byte f);
	public byte pBXor(final R1.F r, final long l, byte f);
	public byte pBLL(final R1.F r, final long l, byte f);
	public byte pBRR(final R1.F r, final long l, byte f);
	public byte pBRRR(final R1.F r, final long l, byte f);
	public char pCAdd(final R1.F r, final long l, char f);
	public char pCSub(final R1.F r, final long l, char f);
	public char pCMul(final R1.F r, final long l, char f);
	public char pCDiv(final R1.F r, final long l, char f);
	public char pCMod(final R1.F r, final long l, char f);
	public char pCAnd(final R1.F r, final long l, char f);
	public char pCOr(final R1.F r, final long l, char f);
	public char pCXor(final R1.F r, final long l, char f);
	public char pCLL(final R1.F r, final long l, char f);
	public char pCRR(final R1.F r, final long l, char f);
	public char pCRRR(final R1.F r, final long l, char f);
	public short pSAdd(final R1.F r, final long l, short f);
	public short pSSub(final R1.F r, final long l, short f);
	public short pSMul(final R1.F r, final long l, short f);
	public short pSDiv(final R1.F r, final long l, short f);
	public short pSMod(final R1.F r, final long l, short f);
	public short pSAnd(final R1.F r, final long l, short f);
	public short pSOr(final R1.F r, final long l, short f);
	public short pSXor(final R1.F r, final long l, short f);
	public short pSLL(final R1.F r, final long l, short f);
	public short pSRR(final R1.F r, final long l, short f);
	public short pSRRR(final R1.F r, final long l, short f);
	public int pIAdd(final R1.F r, final long l, int f);
	public int pISub(final R1.F r, final long l, int f);
	public int pIMul(final R1.F r, final long l, int f);
	public int pIDiv(final R1.F r, final long l, int f);
	public int pIMod(final R1.F r, final long l, int f);
	public int pIAnd(final R1.F r, final long l, int f);
	public int pIOr(final R1.F r, final long l, int f);
	public int pIXor(final R1.F r, final long l, int f);
	public int pILL(final R1.F r, final long l, int f);
	public int pIRR(final R1.F r, final long l, int f);
	public int pIRRR(final R1.F r, final long l, int f);
	public long pJAdd(final R1.F r, final long l, long f);
	public long pJSub(final R1.F r, final long l, long f);
	public long pJMul(final R1.F r, final long l, long f);
	public long pJDiv(final R1.F r, final long l, long f);
	public long pJMod(final R1.F r, final long l, long f);
	public long pJAnd(final R1.F r, final long l, long f);
	public long pJOr(final R1.F r, final long l, long f);
	public long pJXor(final R1.F r, final long l, long f);
	public long pJLL(final R1.F r, final long l, long f);
	public long pJRR(final R1.F r, final long l, long f);
	public long pJRRR(final R1.F r, final long l, long f);
	public float pFAdd(final R1.F r, final long l, float f);
	public float pFSub(final R1.F r, final long l, float f);
	public float pFMul(final R1.F r, final long l, float f);
	public float pFDiv(final R1.F r, final long l, float f);
	public float pFMod(final R1.F r, final long l, float f);
	public double pDAdd(final R1.F r, final long l, double f);
	public double pDSub(final R1.F r, final long l, double f);
	public double pDMul(final R1.F r, final long l, double f);
	public double pDDiv(final R1.F r, final long l, double f);
	public double pDMod(final R1.F r, final long l, double f);
	//-------------------
	public boolean pZAnd(final R1.D r, final long l, boolean f);
	public boolean pZOr(final R1.D r, final long l, boolean f);
	public boolean pZXor(final R1.D r, final long l, boolean f);
	public byte pBAdd(final R1.D r, final long l, byte f);
	public byte pBSub(final R1.D r, final long l, byte f);
	public byte pBMul(final R1.D r, final long l, byte f);
	public byte pBDiv(final R1.D r, final long l, byte f);
	public byte pBMod(final R1.D r, final long l, byte f);
	public byte pBAnd(final R1.D r, final long l, byte f);
	public byte pBOr(final R1.D r, final long l, byte f);
	public byte pBXor(final R1.D r, final long l, byte f);
	public byte pBLL(final R1.D r, final long l, byte f);
	public byte pBRR(final R1.D r, final long l, byte f);
	public byte pBRRR(final R1.D r, final long l, byte f);
	public char pCAdd(final R1.D r, final long l, char f);
	public char pCSub(final R1.D r, final long l, char f);
	public char pCMul(final R1.D r, final long l, char f);
	public char pCDiv(final R1.D r, final long l, char f);
	public char pCMod(final R1.D r, final long l, char f);
	public char pCAnd(final R1.D r, final long l, char f);
	public char pCOr(final R1.D r, final long l, char f);
	public char pCXor(final R1.D r, final long l, char f);
	public char pCLL(final R1.D r, final long l, char f);
	public char pCRR(final R1.D r, final long l, char f);
	public char pCRRR(final R1.D r, final long l, char f);
	public short pSAdd(final R1.D r, final long l, short f);
	public short pSSub(final R1.D r, final long l, short f);
	public short pSMul(final R1.D r, final long l, short f);
	public short pSDiv(final R1.D r, final long l, short f);
	public short pSMod(final R1.D r, final long l, short f);
	public short pSAnd(final R1.D r, final long l, short f);
	public short pSOr(final R1.D r, final long l, short f);
	public short pSXor(final R1.D r, final long l, short f);
	public short pSLL(final R1.D r, final long l, short f);
	public short pSRR(final R1.D r, final long l, short f);
	public short pSRRR(final R1.D r, final long l, short f);
	public int pIAdd(final R1.D r, final long l, int f);
	public int pISub(final R1.D r, final long l, int f);
	public int pIMul(final R1.D r, final long l, int f);
	public int pIDiv(final R1.D r, final long l, int f);
	public int pIMod(final R1.D r, final long l, int f);
	public int pIAnd(final R1.D r, final long l, int f);
	public int pIOr(final R1.D r, final long l, int f);
	public int pIXor(final R1.D r, final long l, int f);
	public int pILL(final R1.D r, final long l, int f);
	public int pIRR(final R1.D r, final long l, int f);
	public int pIRRR(final R1.D r, final long l, int f);
	public long pJAdd(final R1.D r, final long l, long f);
	public long pJSub(final R1.D r, final long l, long f);
	public long pJMul(final R1.D r, final long l, long f);
	public long pJDiv(final R1.D r, final long l, long f);
	public long pJMod(final R1.D r, final long l, long f);
	public long pJAnd(final R1.D r, final long l, long f);
	public long pJOr(final R1.D r, final long l, long f);
	public long pJXor(final R1.D r, final long l, long f);
	public long pJLL(final R1.D r, final long l, long f);
	public long pJRR(final R1.D r, final long l, long f);
	public long pJRRR(final R1.D r, final long l, long f);
	public float pFAdd(final R1.D r, final long l, float f);
	public float pFSub(final R1.D r, final long l, float f);
	public float pFMul(final R1.D r, final long l, float f);
	public float pFDiv(final R1.D r, final long l, float f);
	public float pFMod(final R1.D r, final long l, float f);
	public double pDAdd(final R1.D r, final long l, double f);
	public double pDSub(final R1.D r, final long l, double f);
	public double pDMul(final R1.D r, final long l, double f);
	public double pDDiv(final R1.D r, final long l, double f);
	public double pDMod(final R1.D r, final long l, double f);
	//-------------------


	//-------------------Increment operators
	
	public byte gBPrI(final R1 r, final long l);
	public byte gBPrD(final R1 r, final long l);
	public byte gBPoI(final R1 r, final long l);
	public byte gBPoD(final R1 r, final long l);
	public char gCPrI(final R1 r, final long l);
	public char gCPrD(final R1 r, final long l);
	public char gCPoI(final R1 r, final long l);
	public char gCPoD(final R1 r, final long l);
	public short gSPrI(final R1 r, final long l);
	public short gSPrD(final R1 r, final long l);
	public short gSPoI(final R1 r, final long l);
	public short gSPoD(final R1 r, final long l);
	public int gIPrI(final R1 r, final long l);
	public int gIPrD(final R1 r, final long l);
	public int gIPoI(final R1 r, final long l);
	public int gIPoD(final R1 r, final long l);
	public long gJPrI(final R1 r, final long l);
	public long gJPrD(final R1 r, final long l);
	public long gJPoI(final R1 r, final long l);
	public long gJPoD(final R1 r, final long l);
	public float gFPrI(final R1 r, final long l);
	public float gFPrD(final R1 r, final long l);
	public float gFPoI(final R1 r, final long l);
	public float gFPoD(final R1 r, final long l);
	public double gDPrI(final R1 r, final long l);
	public double gDPrD(final R1 r, final long l);
	public double gDPoI(final R1 r, final long l);
	public double gDPoD(final R1 r, final long l);
	
	public byte gBPrI(final R1.A r, final long l);
	public byte gBPrD(final R1.A r, final long l);
	public byte gBPoI(final R1.A r, final long l);
	public byte gBPoD(final R1.A r, final long l);
	public char gCPrI(final R1.A r, final long l);
	public char gCPrD(final R1.A r, final long l);
	public char gCPoI(final R1.A r, final long l);
	public char gCPoD(final R1.A r, final long l);
	public short gSPrI(final R1.A r, final long l);
	public short gSPrD(final R1.A r, final long l);
	public short gSPoI(final R1.A r, final long l);
	public short gSPoD(final R1.A r, final long l);
	public int gIPrI(final R1.A r, final long l);
	public int gIPrD(final R1.A r, final long l);
	public int gIPoI(final R1.A r, final long l);
	public int gIPoD(final R1.A r, final long l);
	public long gJPrI(final R1.A r, final long l);
	public long gJPrD(final R1.A r, final long l);
	public long gJPoI(final R1.A r, final long l);
	public long gJPoD(final R1.A r, final long l);
	public float gFPrI(final R1.A r, final long l);
	public float gFPrD(final R1.A r, final long l);
	public float gFPoI(final R1.A r, final long l);
	public float gFPoD(final R1.A r, final long l);
	public double gDPrI(final R1.A r, final long l);
	public double gDPrD(final R1.A r, final long l);
	public double gDPoI(final R1.A r, final long l);
	public double gDPoD(final R1.A r, final long l);
	public byte gBPrI(final R1.B r, final long l);
	public byte gBPrD(final R1.B r, final long l);
	public byte gBPoI(final R1.B r, final long l);
	public byte gBPoD(final R1.B r, final long l);
	public char gCPrI(final R1.B r, final long l);
	public char gCPrD(final R1.B r, final long l);
	public char gCPoI(final R1.B r, final long l);
	public char gCPoD(final R1.B r, final long l);
	public short gSPrI(final R1.B r, final long l);
	public short gSPrD(final R1.B r, final long l);
	public short gSPoI(final R1.B r, final long l);
	public short gSPoD(final R1.B r, final long l);
	public int gIPrI(final R1.B r, final long l);
	public int gIPrD(final R1.B r, final long l);
	public int gIPoI(final R1.B r, final long l);
	public int gIPoD(final R1.B r, final long l);
	public long gJPrI(final R1.B r, final long l);
	public long gJPrD(final R1.B r, final long l);
	public long gJPoI(final R1.B r, final long l);
	public long gJPoD(final R1.B r, final long l);
	public float gFPrI(final R1.B r, final long l);
	public float gFPrD(final R1.B r, final long l);
	public float gFPoI(final R1.B r, final long l);
	public float gFPoD(final R1.B r, final long l);
	public double gDPrI(final R1.B r, final long l);
	public double gDPrD(final R1.B r, final long l);
	public double gDPoI(final R1.B r, final long l);
	public double gDPoD(final R1.B r, final long l);
	public byte gBPrI(final R1.C r, final long l);
	public byte gBPrD(final R1.C r, final long l);
	public byte gBPoI(final R1.C r, final long l);
	public byte gBPoD(final R1.C r, final long l);
	public char gCPrI(final R1.C r, final long l);
	public char gCPrD(final R1.C r, final long l);
	public char gCPoI(final R1.C r, final long l);
	public char gCPoD(final R1.C r, final long l);
	public short gSPrI(final R1.C r, final long l);
	public short gSPrD(final R1.C r, final long l);
	public short gSPoI(final R1.C r, final long l);
	public short gSPoD(final R1.C r, final long l);
	public int gIPrI(final R1.C r, final long l);
	public int gIPrD(final R1.C r, final long l);
	public int gIPoI(final R1.C r, final long l);
	public int gIPoD(final R1.C r, final long l);
	public long gJPrI(final R1.C r, final long l);
	public long gJPrD(final R1.C r, final long l);
	public long gJPoI(final R1.C r, final long l);
	public long gJPoD(final R1.C r, final long l);
	public float gFPrI(final R1.C r, final long l);
	public float gFPrD(final R1.C r, final long l);
	public float gFPoI(final R1.C r, final long l);
	public float gFPoD(final R1.C r, final long l);
	public double gDPrI(final R1.C r, final long l);
	public double gDPrD(final R1.C r, final long l);
	public double gDPoI(final R1.C r, final long l);
	public double gDPoD(final R1.C r, final long l);
	public byte gBPrI(final R1.S r, final long l);
	public byte gBPrD(final R1.S r, final long l);
	public byte gBPoI(final R1.S r, final long l);
	public byte gBPoD(final R1.S r, final long l);
	public char gCPrI(final R1.S r, final long l);
	public char gCPrD(final R1.S r, final long l);
	public char gCPoI(final R1.S r, final long l);
	public char gCPoD(final R1.S r, final long l);
	public short gSPrI(final R1.S r, final long l);
	public short gSPrD(final R1.S r, final long l);
	public short gSPoI(final R1.S r, final long l);
	public short gSPoD(final R1.S r, final long l);
	public int gIPrI(final R1.S r, final long l);
	public int gIPrD(final R1.S r, final long l);
	public int gIPoI(final R1.S r, final long l);
	public int gIPoD(final R1.S r, final long l);
	public long gJPrI(final R1.S r, final long l);
	public long gJPrD(final R1.S r, final long l);
	public long gJPoI(final R1.S r, final long l);
	public long gJPoD(final R1.S r, final long l);
	public float gFPrI(final R1.S r, final long l);
	public float gFPrD(final R1.S r, final long l);
	public float gFPoI(final R1.S r, final long l);
	public float gFPoD(final R1.S r, final long l);
	public double gDPrI(final R1.S r, final long l);
	public double gDPrD(final R1.S r, final long l);
	public double gDPoI(final R1.S r, final long l);
	public double gDPoD(final R1.S r, final long l);
	public byte gBPrI(final R1.I r, final long l);
	public byte gBPrD(final R1.I r, final long l);
	public byte gBPoI(final R1.I r, final long l);
	public byte gBPoD(final R1.I r, final long l);
	public char gCPrI(final R1.I r, final long l);
	public char gCPrD(final R1.I r, final long l);
	public char gCPoI(final R1.I r, final long l);
	public char gCPoD(final R1.I r, final long l);
	public short gSPrI(final R1.I r, final long l);
	public short gSPrD(final R1.I r, final long l);
	public short gSPoI(final R1.I r, final long l);
	public short gSPoD(final R1.I r, final long l);
	public int gIPrI(final R1.I r, final long l);
	public int gIPrD(final R1.I r, final long l);
	public int gIPoI(final R1.I r, final long l);
	public int gIPoD(final R1.I r, final long l);
	public long gJPrI(final R1.I r, final long l);
	public long gJPrD(final R1.I r, final long l);
	public long gJPoI(final R1.I r, final long l);
	public long gJPoD(final R1.I r, final long l);
	public float gFPrI(final R1.I r, final long l);
	public float gFPrD(final R1.I r, final long l);
	public float gFPoI(final R1.I r, final long l);
	public float gFPoD(final R1.I r, final long l);
	public double gDPrI(final R1.I r, final long l);
	public double gDPrD(final R1.I r, final long l);
	public double gDPoI(final R1.I r, final long l);
	public double gDPoD(final R1.I r, final long l);
	public byte gBPrI(final R1.L r, final long l);
	public byte gBPrD(final R1.L r, final long l);
	public byte gBPoI(final R1.L r, final long l);
	public byte gBPoD(final R1.L r, final long l);
	public char gCPrI(final R1.L r, final long l);
	public char gCPrD(final R1.L r, final long l);
	public char gCPoI(final R1.L r, final long l);
	public char gCPoD(final R1.L r, final long l);
	public short gSPrI(final R1.L r, final long l);
	public short gSPrD(final R1.L r, final long l);
	public short gSPoI(final R1.L r, final long l);
	public short gSPoD(final R1.L r, final long l);
	public int gIPrI(final R1.L r, final long l);
	public int gIPrD(final R1.L r, final long l);
	public int gIPoI(final R1.L r, final long l);
	public int gIPoD(final R1.L r, final long l);
	public long gJPrI(final R1.L r, final long l);
	public long gJPrD(final R1.L r, final long l);
	public long gJPoI(final R1.L r, final long l);
	public long gJPoD(final R1.L r, final long l);
	public float gFPrI(final R1.L r, final long l);
	public float gFPrD(final R1.L r, final long l);
	public float gFPoI(final R1.L r, final long l);
	public float gFPoD(final R1.L r, final long l);
	public double gDPrI(final R1.L r, final long l);
	public double gDPrD(final R1.L r, final long l);
	public double gDPoI(final R1.L r, final long l);
	public double gDPoD(final R1.L r, final long l);
	public byte gBPrI(final R1.F r, final long l);
	public byte gBPrD(final R1.F r, final long l);
	public byte gBPoI(final R1.F r, final long l);
	public byte gBPoD(final R1.F r, final long l);
	public char gCPrI(final R1.F r, final long l);
	public char gCPrD(final R1.F r, final long l);
	public char gCPoI(final R1.F r, final long l);
	public char gCPoD(final R1.F r, final long l);
	public short gSPrI(final R1.F r, final long l);
	public short gSPrD(final R1.F r, final long l);
	public short gSPoI(final R1.F r, final long l);
	public short gSPoD(final R1.F r, final long l);
	public int gIPrI(final R1.F r, final long l);
	public int gIPrD(final R1.F r, final long l);
	public int gIPoI(final R1.F r, final long l);
	public int gIPoD(final R1.F r, final long l);
	public long gJPrI(final R1.F r, final long l);
	public long gJPrD(final R1.F r, final long l);
	public long gJPoI(final R1.F r, final long l);
	public long gJPoD(final R1.F r, final long l);
	public float gFPrI(final R1.F r, final long l);
	public float gFPrD(final R1.F r, final long l);
	public float gFPoI(final R1.F r, final long l);
	public float gFPoD(final R1.F r, final long l);
	public double gDPrI(final R1.F r, final long l);
	public double gDPrD(final R1.F r, final long l);
	public double gDPoI(final R1.F r, final long l);
	public double gDPoD(final R1.F r, final long l);
	public byte gBPrI(final R1.D r, final long l);
	public byte gBPrD(final R1.D r, final long l);
	public byte gBPoI(final R1.D r, final long l);
	public byte gBPoD(final R1.D r, final long l);
	public char gCPrI(final R1.D r, final long l);
	public char gCPrD(final R1.D r, final long l);
	public char gCPoI(final R1.D r, final long l);
	public char gCPoD(final R1.D r, final long l);
	public short gSPrI(final R1.D r, final long l);
	public short gSPrD(final R1.D r, final long l);
	public short gSPoI(final R1.D r, final long l);
	public short gSPoD(final R1.D r, final long l);
	public int gIPrI(final R1.D r, final long l);
	public int gIPrD(final R1.D r, final long l);
	public int gIPoI(final R1.D r, final long l);
	public int gIPoD(final R1.D r, final long l);
	public long gJPrI(final R1.D r, final long l);
	public long gJPrD(final R1.D r, final long l);
	public long gJPoI(final R1.D r, final long l);
	public long gJPoD(final R1.D r, final long l);
	public float gFPrI(final R1.D r, final long l);
	public float gFPrD(final R1.D r, final long l);
	public float gFPoI(final R1.D r, final long l);
	public float gFPoD(final R1.D r, final long l);
	public double gDPrI(final R1.D r, final long l);
	public double gDPrD(final R1.D r, final long l);
	public double gDPoI(final R1.D r, final long l);
	public double gDPoD(final R1.D r, final long l);
	public byte gBPrI(final R1.N r, final long l);
	public byte gBPrD(final R1.N r, final long l);
	public byte gBPoI(final R1.N r, final long l);
	public byte gBPoD(final R1.N r, final long l);
	public char gCPrI(final R1.N r, final long l);
	public char gCPrD(final R1.N r, final long l);
	public char gCPoI(final R1.N r, final long l);
	public char gCPoD(final R1.N r, final long l);
	public short gSPrI(final R1.N r, final long l);
	public short gSPrD(final R1.N r, final long l);
	public short gSPoI(final R1.N r, final long l);
	public short gSPoD(final R1.N r, final long l);
	public int gIPrI(final R1.N r, final long l);
	public int gIPrD(final R1.N r, final long l);
	public int gIPoI(final R1.N r, final long l);
	public int gIPoD(final R1.N r, final long l);
	public long gJPrI(final R1.N r, final long l);
	public long gJPrD(final R1.N r, final long l);
	public long gJPoI(final R1.N r, final long l);
	public long gJPoD(final R1.N r, final long l);
	public float gFPrI(final R1.N r, final long l);
	public float gFPrD(final R1.N r, final long l);
	public float gFPoI(final R1.N r, final long l);
	public float gFPoD(final R1.N r, final long l);
	public double gDPrI(final R1.N r, final long l);
	public double gDPrD(final R1.N r, final long l);
	public double gDPoI(final R1.N r, final long l);
	public double gDPoD(final R1.N r, final long l);
	
}
